Feature/implement entity
weebNeedWeed/TeenBoutique pull request #7
Opened 2023-09-30 14:19 UTC by Rocky-cyberclop

Merge will get bugs or not?

2023-09-30 14:45 UTC, Rocky-cyberclop reviewed
No conflit found

2023-09-30 14:58 UTC, weebNeedWeed requested changes
Em chua submit @Rocky-cyberclop 🤡

2023-09-30 14:58 UTC, weebNeedWeed commented on backend/src/main/java/com/teenboutique/web/entities/Employee.java
> +	private Role permission;
lỗi field

2023-09-30 14:58 UTC, weebNeedWeed commented on backend/src/main/java/com/teenboutique/web/entities/Bill.java
> +	private Set<BillItem> billItems = new HashSet<>();
Thay tất cả set trong one to many thành list (lý do: list có performance tốt hơn https://docs.jboss.org/hibernate/orm/4.3/manual/en-US/html/ch20.html#performance-collections-mostefficentinverse)

2023-09-30 14:58 UTC, weebNeedWeed commented on backend/src/main/java/com/teenboutique/web/entities/BillItem.java
> +public class BillItem {
Thay bill thành order

2023-09-30 15:00 UTC, Rocky-cyberclop commented on backend/src/main/java/com/teenboutique/web/entities/BillItem.java
> +public class BillItem {
Lỗi trùng từ khóa mysql

2023-09-30 15:12 UTC, Rocky-cyberclop commented on backend/src/main/java/com/teenboutique/web/entities/Employee.java
> +	private Role permission;
cụ thể hơn đi

2023-09-30 15:14 UTC, weebNeedWeed commented on backend/src/main/java/com/teenboutique/web/entities/Employee.java
> +	private Role permission;
private Role role;

2023-09-30 15:30 UTC, weebNeedWeed requested changes

2023-09-30 15:30 UTC, weebNeedWeed commented on backend/src/main/java/com/teenboutique/web/entities/Bill.java
> +public class Bill {
Đổi tên thành Order

2023-09-30 15:30 UTC, weebNeedWeed commented on backend/src/main/java/com/teenboutique/web/entities/BillItem.java
> +public class BillItem {
OrderItem

2023-09-30 15:30 UTC, weebNeedWeed commented on backend/src/main/java/com/teenboutique/web/entities/Category.java
> +	@OneToMany(cascade = CascadeType.ALL, mappedBy = "category", orphanRemoval = true)
Set -> List

2023-09-30 15:30 UTC, weebNeedWeed commented on backend/src/main/java/com/teenboutique/web/entities/Category.java
> +	@OneToMany(cascade = CascadeType.ALL, mappedBy = "category", orphanRemoval = true)
thay cascase.ALL

2023-09-30 15:30 UTC, weebNeedWeed commented on backend/src/main/java/com/teenboutique/web/entities/Customer.java
> +	private Set<Bill> bills = new HashSet<>();
list

2023-09-30 15:30 UTC, weebNeedWeed commented on backend/src/main/java/com/teenboutique/web/entities/Customer.java
> +	private Set<CartItem> cartItems = new HashSet<>();
list

2023-09-30 15:30 UTC, weebNeedWeed commented on backend/src/main/java/com/teenboutique/web/entities/Employee.java
> +	private Set<Bill> bills = new HashSet<>();
list of order

2023-09-30 15:30 UTC, weebNeedWeed commented on backend/src/main/java/com/teenboutique/web/entities/BillItem.java
> +	private Bill bill;
Order, thừa mapsId

**Definition of mapsId:**
> Designates a ManyToOne or OneToOne relationship attribute that provides the mapping for an EmbeddedId primary key, an attribute within an EmbeddedId primary key, or a simple primary key of the parent entity. The value element specifies the attribute within a composite key to which the relationship attribute corresponds. If the entity's primary key is of the same Java type as the primary key of the entity referenced by the relationship, the value attribute is not specified.

2023-09-30 15:30 UTC, weebNeedWeed commented on backend/src/main/java/com/teenboutique/web/entities/Employee.java
> +	private LocalDate starting_date;
anh viết theo kiểu camelCase (startingDate) là bên kia tự động map thành starting_date

2023-09-30 15:30 UTC, weebNeedWeed commented on backend/src/main/java/com/teenboutique/web/entities/Product.java
> +	private long price;
price nên dùng double hoặc float

2023-09-30 15:30 UTC, weebNeedWeed commented on backend/src/main/java/com/teenboutique/web/entities/Size.java
> +	private long id;
nên dùng Long 
![image](https://github.com/weebNeedWeed/TeenBoutique/assets/29837447/7da7e65f-f6c2-4e4a-9f6a-340b60b8bcc9)

2023-09-30 15:30 UTC, weebNeedWeed commented on backend/src/main/java/com/teenboutique/web/entities/Role.java
> +	private Set<Employee> staffs = new HashSet<>();
list

2023-09-30 15:30 UTC, weebNeedWeed commented on backend/src/main/java/com/teenboutique/web/entities/ProductDetail.java
> +	@MapsId("product_id")
thừa mapsId nếu dùng cách này

2023-09-30 15:30 UTC, weebNeedWeed commented on backend/src/main/java/com/teenboutique/web/entities/ProductDetail.java
> +	@MapsId("size_id")
Như trên

2023-09-30 15:30 UTC, weebNeedWeed commented on backend/src/main/java/com/teenboutique/web/entities/ProductDetail.java
> +	private Set<CartItem> cartItems = new HashSet<>();
list

2023-09-30 15:30 UTC, weebNeedWeed commented on backend/src/main/java/com/teenboutique/web/entities/ProductDetail.java
> +	private Set<BillItem> billItems = new HashSet<>();
list

2023-09-30 15:30 UTC, Rocky-cyberclop commented on backend/src/main/java/com/teenboutique/web/entities/Bill.java
> +public class Bill {
Trùng ký tự đặc biệt mysql

2023-09-30 15:31 UTC, Rocky-cyberclop commented on backend/src/main/java/com/teenboutique/web/entities/BillItem.java
> +public class BillItem {
Trùng tan là hiện tượng cả gia đình đột ngột qua đời trong đêm

2023-09-30 15:31 UTC, Rocky-cyberclop commented on backend/src/main/java/com/teenboutique/web/entities/Category.java
> +	@OneToMany(cascade = CascadeType.ALL, mappedBy = "category", orphanRemoval = true)
Done

2023-09-30 15:32 UTC, Rocky-cyberclop commented on backend/src/main/java/com/teenboutique/web/entities/Category.java
> +	@OneToMany(cascade = CascadeType.ALL, mappedBy = "category", orphanRemoval = true)
Đổi thành gì

2023-09-30 15:32 UTC, Rocky-cyberclop commented on backend/src/main/java/com/teenboutique/web/entities/Customer.java
> +	private Set<Bill> bills = new HashSet<>();
done

2023-09-30 15:32 UTC, Rocky-cyberclop commented on backend/src/main/java/com/teenboutique/web/entities/Customer.java
> +	private Set<CartItem> cartItems = new HashSet<>();
done

2023-09-30 15:32 UTC, Rocky-cyberclop commented on backend/src/main/java/com/teenboutique/web/entities/Employee.java
> +	private Set<Bill> bills = new HashSet<>();
doen

2023-09-30 15:33 UTC, Rocky-cyberclop commented on backend/src/main/java/com/teenboutique/web/entities/Employee.java
> +	private LocalDate starting_date;
thích viết v

2023-09-30 15:33 UTC, weebNeedWeed commented on backend/src/main/java/com/teenboutique/web/entities/Category.java
> +	@OneToMany(cascade = CascadeType.ALL, mappedBy = "category", orphanRemoval = true)
merge + persist

2023-09-30 15:34 UTC, weebNeedWeed commented on backend/src/main/java/com/teenboutique/web/entities/BillItem.java
> +	private Bill bill;
https://stackoverflow.com/questions/9923643/can-someone-please-explain-me-mapsid-in-hibernate @Rocky-cyberclop

2023-09-30 15:34 UTC, weebNeedWeed commented on backend/src/main/java/com/teenboutique/web/entities/Employee.java
> +	private LocalDate starting_date;
khác convention ạ

2023-09-30 15:34 UTC, Rocky-cyberclop commented on backend/src/main/java/com/teenboutique/web/entities/Product.java
> +	private long price;
cụ thể hơn vì sao đi, dùng long vì a nghĩ là giá tiền VND thì k có phẩy

2023-09-30 15:36 UTC, Rocky-cyberclop commented on backend/src/main/java/com/teenboutique/web/entities/Role.java
> +	private Set<Employee> staffs = new HashSet<>();
done

2023-09-30 15:36 UTC, Rocky-cyberclop commented on backend/src/main/java/com/teenboutique/web/entities/Size.java
> +	private long id;
thế có cần đổi hết id lại k

2023-09-30 15:37 UTC, Rocky-cyberclop commented on backend/src/main/java/com/teenboutique/web/entities/ProductDetail.java
> +	private Set<CartItem> cartItems = new HashSet<>();
done

2023-09-30 15:37 UTC, Rocky-cyberclop commented on backend/src/main/java/com/teenboutique/web/entities/ProductDetail.java
> +	private Set<BillItem> billItems = new HashSet<>();
done

2023-09-30 15:37 UTC, weebNeedWeed commented on backend/src/main/java/com/teenboutique/web/entities/Bill.java
> +public class Bill {
anh query bằng jpa mà

2023-09-30 15:37 UTC, weebNeedWeed commented on backend/src/main/java/com/teenboutique/web/entities/Bill.java
> +public class Bill {
@Rocky-cyberclop đổi sang order đi ạ

2023-09-30 15:40 UTC, weebNeedWeed commented on backend/src/main/java/com/teenboutique/web/entities/Bill.java
> +public class Bill {
@Rocky-cyberclop trong mysql nếu nó lỗi order thì anh thêm `` vào: select * from `Order`
Bill ở đây ngữ nghĩa khác hoàn toàn

2023-09-30 16:23 UTC, Rocky-cyberclop commented on backend/src/main/java/com/teenboutique/web/entities/BillItem.java
> +	private Bill bill;
done

2023-09-30 16:23 UTC, Rocky-cyberclop commented on backend/src/main/java/com/teenboutique/web/entities/ProductDetail.java
> +	@MapsId("product_id")
done

2023-09-30 16:23 UTC, Rocky-cyberclop commented on backend/src/main/java/com/teenboutique/web/entities/ProductDetail.java
> +	@MapsId("size_id")
done

2023-09-30 16:24 UTC, Rocky-cyberclop commented on backend/src/main/java/com/teenboutique/web/entities/Bill.java
> +public class Bill {
done

2023-09-30 16:24 UTC, Rocky-cyberclop commented on backend/src/main/java/com/teenboutique/web/entities/BillItem.java
> +public class BillItem {
done

2023-09-30 16:25 UTC, Rocky-cyberclop commented on backend/src/main/java/com/teenboutique/web/entities/Category.java
> +	@OneToMany(cascade = CascadeType.ALL, mappedBy = "category", orphanRemoval = true)
một trong 2 thôi pk

2023-09-30 16:26 UTC, Rocky-cyberclop commented on backend/src/main/java/com/teenboutique/web/entities/Employee.java
> +	private LocalDate starting_date;
khỏi sửa đc k nó đâu ảnh hưởng mấy

2023-09-30 16:38 UTC, weebNeedWeed commented on backend/src/main/java/com/teenboutique/web/entities/Order.java
> +@Table(name = "Bill")
name dùng orders

2023-09-30 16:38 UTC, weebNeedWeed commented on backend/src/main/java/com/teenboutique/web/entities/CartItem.java
> +@Table(name = "CartItem")
ở mấy chỗ anh dùng foreign key là kiểu snake_case, ví dụ: size_id. Tên bảng cũng sẽ tương tự => cart_item
vì bảng là tập hợp những thể hiện của 1 entity nào đó, nên bảng sẽ dùng số nhiều => cart_items

2023-09-30 16:38 UTC, weebNeedWeed commented on backend/src/main/java/com/teenboutique/web/entities/CartItem.java
> +@Table(name = "CartItem")
@Rocky-cyberclop

2023-09-30 16:38 UTC, weebNeedWeed commented on backend/src/main/java/com/teenboutique/web/entities/Product.java
> +	private long price;
thế long cũng được

2023-09-30 16:38 UTC, weebNeedWeed commented on backend/src/main/java/com/teenboutique/web/entities/Employee.java
> +	private LocalDate starting_date;
không ảnh hưởng nhưng cũng không được ạ

2023-09-30 16:38 UTC, weebNeedWeed commented on backend/src/main/java/com/teenboutique/web/entities/Category.java
> +	@OneToMany(cascade = CascadeType.ALL, mappedBy = "category", orphanRemoval = true)
@Rocky-cyberclop có thể cả 2 cũng được 
```java
cascade = {CascadeType.PERSIST, CascadeType.MERGE}
```

2023-09-30 16:38 UTC, weebNeedWeed commented on backend/src/main/java/com/teenboutique/web/entities/CartItem.java
> +@Table(name = "CartItem")
![image](https://github.com/weebNeedWeed/TeenBoutique/assets/29837447/d1dbb92d-e532-4bbb-aba1-02fef4dff6a9)

2023-09-30 16:51 UTC, Rocky-cyberclop commented on backend/src/main/java/com/teenboutique/web/entities/Category.java
> +	@OneToMany(cascade = CascadeType.ALL, mappedBy = "category", orphanRemoval = true)
done

2023-09-30 16:52 UTC, Rocky-cyberclop commented on backend/src/main/java/com/teenboutique/web/entities/Employee.java
> +	private LocalDate starting_date;
thế chỗ nào snake đổi thành camel hết đúng k

2023-09-30 16:53 UTC, Rocky-cyberclop commented on backend/src/main/java/com/teenboutique/web/entities/Size.java
> +	private long id;
hello

2023-10-01 02:48 UTC, weebNeedWeed requested changes

2023-10-01 02:48 UTC, weebNeedWeed commented on backend/src/main/java/com/teenboutique/web/entities/OrderItem.java
> +	@MapsId("bill_id")
Dư mapsId ạ

2023-10-01 02:48 UTC, weebNeedWeed commented on backend/src/main/java/com/teenboutique/web/entities/CartItem.java
> +	@MapsId("customer_id")
dư mapsId

2023-10-01 03:38 UTC, Rocky-cyberclop commented on backend/src/main/java/com/teenboutique/web/entities/Employee.java
> +	private LocalDate starting_date;
done

2023-10-01 03:38 UTC, Rocky-cyberclop commented on backend/src/main/java/com/teenboutique/web/entities/Size.java
> +	private long id;
done

2023-10-01 03:38 UTC, Rocky-cyberclop commented on backend/src/main/java/com/teenboutique/web/entities/Order.java
> +@Table(name = "Bill")
done

2023-10-01 03:52 UTC, Rocky-cyberclop commented on backend/src/main/java/com/teenboutique/web/entities/OrderItem.java
> +	@MapsId("bill_id")
done

2023-10-01 03:56 UTC, Rocky-cyberclop commented on backend/src/main/java/com/teenboutique/web/entities/CartItem.java
> +	@MapsId("customer_id")
done

2023-10-01 04:14 UTC, weebNeedWeed requested changes

2023-10-01 04:14 UTC, weebNeedWeed commented on backend/src/main/java/com/teenboutique/web/entities/CustomerOrderItem.java
> +		private long customer_order_id;
@Rocky-cyberclop

2023-10-01 04:14 UTC, weebNeedWeed commented on backend/src/main/java/com/teenboutique/web/entities/CustomerOrderItem.java
> +		private long customer_order_id;
Long ạ

2023-10-01 04:14 UTC, weebNeedWeed commented on backend/src/main/java/com/teenboutique/web/entities/Employee.java
> +	private List<CustomerOrder> bills = new ArrayList<>();
Sai tên ạ

2023-10-01 04:14 UTC, weebNeedWeed commented on backend/src/main/java/com/teenboutique/web/entities/CustomerOrder.java
> +	private Employee staff;
Here

2023-10-01 04:18 UTC, weebNeedWeed requested changes

2023-10-01 04:18 UTC, weebNeedWeed commented on backend/src/main/java/com/teenboutique/web/entities/Customer.java
> +	private List<CustomerOrder> bills = new ArrayList<>();
đây ạ

2023-10-01 04:18 UTC, weebNeedWeed commented on backend/src/main/java/com/teenboutique/web/entities/Employee.java
> +	private List<CustomerOrder> bills = new ArrayList<>();
Order

2023-10-01 04:18 UTC, weebNeedWeed commented on backend/src/main/java/com/teenboutique/web/entities/ProductDetail.java
> +	private List<CustomerOrderItem> billItems = new ArrayList<>();
order

2023-10-01 04:18 UTC, weebNeedWeed commented on backend/src/main/java/com/teenboutique/web/entities/Role.java
> +	private List<Employee> staffs = new ArrayList<>();
employees

2023-10-01 04:20 UTC, Rocky-cyberclop commented on backend/src/main/java/com/teenboutique/web/entities/CustomerOrderItem.java
> +		private long customer_order_id;
done

2023-10-01 04:20 UTC, Rocky-cyberclop commented on backend/src/main/java/com/teenboutique/web/entities/CustomerOrderItem.java
> +		private long customer_order_id;
này vừa sửa trc khi e submit review r

2023-10-01 04:32 UTC, Rocky-cyberclop commented on backend/src/main/java/com/teenboutique/web/entities/Employee.java
> +	private List<CustomerOrder> bills = new ArrayList<>();
done

2023-10-01 04:33 UTC, Rocky-cyberclop commented on backend/src/main/java/com/teenboutique/web/entities/CustomerOrder.java
> +	private Employee staff;
done

2023-10-01 04:34 UTC, Rocky-cyberclop commented on backend/src/main/java/com/teenboutique/web/entities/Customer.java
> +	private List<CustomerOrder> bills = new ArrayList<>();
done

2023-10-01 04:35 UTC, Rocky-cyberclop commented on backend/src/main/java/com/teenboutique/web/entities/Employee.java
> +	private List<CustomerOrder> bills = new ArrayList<>();
done

2023-10-01 04:35 UTC, Rocky-cyberclop commented on backend/src/main/java/com/teenboutique/web/entities/ProductDetail.java
> +	private List<CustomerOrderItem> billItems = new ArrayList<>();
done

2023-10-01 04:35 UTC, Rocky-cyberclop commented on backend/src/main/java/com/teenboutique/web/entities/Role.java
> +	private List<Employee> staffs = new ArrayList<>();
done

2023-10-01 04:51 UTC, weebNeedWeed approved these changes

2023-10-01 05:12 UTC, merged